### ISSUE TITLE
Can't get position data when entity created.

### ISSUE THREAD

**Issue by JustVic** [zpl-c/librg#38]
Can't get position data when entity created. In example example-enet.c I try to get position in client_read_create function but librg_event_size_get always returns actual_length 0.

`librg_event_set(world, LIBRG_READ_CREATE, client_read_create);`

```
int32_t client_read_create(librg_world *w, librg_event *e) {
    int64_t owner_id = librg_event_owner_get(w, e);
    int64_t entity_id = librg_event_entity_get(w, e);
    printf("[client] An entity %d was created for owner: %d\n", (int)entity_id, (int)owner_id);
   
    size_t actual_length = librg_event_size_get(w, e);
    printf("[client] actual_length = %zu", actual_length);
    if (actual_length != sizeof(vec3)) return 0;
   
    char *buffer = librg_event_buffer_get(w, e);
    
    vec3 position = {0};
    memcpy(&position, buffer, actual_length);

    return 0;
}

```

**Comment by JustVic** [comment]
Sorry. I resolve this. It's just my misunderstanding of how library works.

**Comment by inlife** [comment]
Hey @JustVic 

Added a new illustration showcasing the protocol. Please take a look, might be helpful: ![](https://user-images.githubusercontent.com/2182108/181924764-3ac8b765-f7a8-4fe0-a713-3928d53a413c.png)
