### ISSUE TITLE
How to properly install and add this lib to C++ project?

### ISSUE THREAD

**Issue by JustVic** [zpl-c/librg#39]
The documentation says just to include "librg.h".  But when I do just that and add this to my c++ project I got error:
```
librg/code/source/query.c: In function ‘int32_t librg_world_fetch_chunk(librg_world*, librg_chunk, int64_t*, size_t*)’:
error: taking address of temporary array
    39 |    return librg_world_fetch_chunkarray(world, (librg_chunk[]){chunk}, 1, entity_ids, entity_amount);
      |                                                                                                  ^~~~~~~
```

What I need to do to inlude library in c++ project? Maybe somehow link library like -lrg. Maybe I need add include some directories -I./librg/code. Or maybe I need to install somehow compiled lib. I use Ubuntu linux.

**Comment by inlife** [comment]
To start using the library, all you need to do is to download the librg.h file from the releases: 
https://github.com/zpl-c/librg/releases/

**Comment by zaklaus** [comment]
Hi, could you try to compile the example with the `-std=gnu11` enabled?

**Comment by JustVic** [comment]
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04) . Standart Ubuntu versions from apt.` -std=gnu11` flag did not produce any effect. Perhaps it has something to do with the fact that the library is on C and I'm trying to connect it to a C++ project,ы but I used to do this with other libraries like SDL2 connected to the C++ project m and everything was going fine.

**Comment by JustVic** [comment]
Thanks a lot. Will see what you can do. When I remove all from C++ in this hello world and try to build it like pure C and everything was built fine like expected.

**Comment by inlife** [comment]
Hey @JustVic 

Pushed a commit that should help you: b0af4ec7051961d0a5accb0cd4242a5bcfa6843a
