### ISSUE TITLE
Emscripten Information

### ISSUE THREAD

**Issue by ClosetMonkey** [zpl-c/librg#4]
Can you post some examples or at least some notes regarding the projects emscripten port?

**Comment by inlife** [comment]
hello, im not sure that this is possible at the moment
as far as i know, emscripten targets browser api, which doesn't have any alternative to UDP protocol used in enet (one of our core dependencies)
thus it will be not usable

**Comment by ClosetMonkey** [comment]
(disclaimer: I hardly know jack about emscripten...) emscripten is able to access extension apis such as chrome sockets such as in the enet-npm emscripten build, but the reason I ask is because librg has an emscripten build file at scripts/build-emscripten.sh but no further information.

**Comment by inlife** [comment]
Hmm interesting, didn't know that. Gonna try borrowing enet-npm's makefile, and maybe bringing emscripten librg to life, if im lucky :D

**Comment by inlife** [comment]
so from what i understood, we need to integrate 2 jsified libraries:
* https://github.com/mnaamani/enet-npm/blob/master/src/library_inet.js
* https://github.com/mnaamani/enet-npm/blob/master/src/library_node_sockets.js

then, probably create quite a couple of wrappers, and only then we will be able to compile it replicating instructions from the Makefile:
* https://github.com/mnaamani/enet-npm/blob/master/Makefile

**Comment by zaklaus** [comment]
Closing, emscripten support is now available. :)
