### ISSUE TITLE
How to generate different ID for different clients?

### ISSUE THREAD

**Issue by JustVic** [zpl-c/librg#40]
Just a question. In example-enet.c server and all clients in one file and ID's generation is easy:
```
        for (int i = 0; i < MAX_CLIENTS; ++i) {
            client_update(i, clients[i]);
        }
```
in that case i is ID.
But in real case clients on different computers don't  know about each other and therefore can't generate id's by itself.
But to recieve(read) something or to send(write) something it needs an ID as I understand.        
```
   librg_world_read(
        world,
        ID,
        (char *)event.packet->data,
        event.packet->dataLength,
        NULL
    );

    librg_world_write(
        world,
        ID,
        buffer,
        &buffer_length,
        NULL
    );
```
I assume It's somehow must be generation on server.
How to generate different ID for different clients?
Maybe It's silly question and I don't understand something...

**Comment by JustVic** [comment]
I assume it needs to use enet peer->outgoingPeerID but client get it after first client_update(ENetPeer *)librg_world_userdata_get(world);).

**Comment by inlife** [comment]
Please take a look at this comment from the [this example code](https://zpl-c.github.io/librg/#/defs/packing?id=example-1):

```c
    /* owner id does not have to match original owner id from example-packing.c */
    /* think of it as a owner translation, if you encoded data for owner 42 */
    /* the one who reads on this side will be the one who was supposed to read it */
    /* even if his local owner id will be different from original value on other side */
    /* but for simplicity sake, we will keep it here 42 as well */
```

Clients do not care which Id will be used for reading the incoming world, for simplicity sake it can always be 0 for every client locally.

**Comment by inlife** [comment]
Closing issue as resolved
