### ISSUE TITLE
Ownership information in reader OnCreate event

### ISSUE THREAD

**Issue by JustVic** [zpl-c/librg#41]
In clients librg_event_owner_get(w, e) in client_read_create or client_read_update owner_id always the same for all entities_id.
I tested it in example-enet.c. Maybe it work like expected, but in that case client can't get real owner of entity... Maybe it's more related with enet than librg.

**Comment by inlife** [comment]
That is most likely related to the fact that the method `librg_event_owner_get` returns the owner for whom the event is being called. At the moment, on the reader side, replicated entities by default are created with owner `LIBRG_OWNER_INVALID`. And only later, the actual owner is set.

I'll think about possible ideas on how to improve that approach.

**Comment by inlife** [comment]
Actually, after some thinking, we found a way to do that w/o any major modifications. And published it as a part of `v7.0.1`!

Now using `librg_entity_owner_get` will give you the owner of the entity, and if it matches the one in `librg_event_owner_get`, it is the entity owned by the client!

**Comment by zpl-zak** [comment]
Hey @Mormert ,

sorry for the late response! This indeed seems to be behaving incorrectly, we will get back to you with a solution a bit later.

Thanks!

**Comment by Mormert** [comment]
> Hey @Mormert ,
> 
> sorry for the late response! This indeed seems to be behaving incorrectly, we will get back to you with a solution a bit later.
> 
> Thanks!

Thank you, let me know if you need help or assistance!

**Comment by Mormert** [comment]
Just a simple showcase based on the example-enet.c provided.
Change the function <i>client_read_create</i> to this:

```c
int32_t client_read_create(librg_world *w, librg_event *e) {
    int64_t owner_id = librg_event_owner_get(w, e);
    int64_t entity_id = librg_event_entity_get(w, e);
    int64_t entity_owner = librg_entity_owner_get(w,entity_id);
    printf("[client] An entity %d was created for owner: %d (with owner %d)\n", (int)entity_id, (int)owner_id, (int)entity_owner);
    return 0;
}
```

And the output will be similar to:
```
[client] An entity 1 was created for owner: 0 (with owner -2)
[client] An entity 2 was removed for owner: 0
[client] An entity 0 was created for owner: 1 (with owner -2)
[client] An entity 0 was removed for owner: 2
[client] An entity 2 was created for owner: 0 (with owner -2)
[client] An entity 0 was created for owner: 2 (with owner -2)
```

**Comment by inlife** [comment]
Hey there @Mormert 

From the design perspective, it seems to work as intended. The real reason the owner function returns an incorrect value for the entity is that the "reader" of the world snapshot does not know anything about other ownerships outside of its own. The owner ID is never even packed into the buffer for any of the entities, for any owner. So the "reader" can only know about ownership of their own entities and no others.

To add that support, as the most straightforward option, you can leverage the `event->buffer`, write the desired value there on the "writer" side, and then read it back on the "reader" side for all entities that you wish.

Does it make sense?

**Comment by Mormert** [comment]
@inlife ,
> Hey there @Mormert
> 
> From the design perspective, it seems to work as intended. The real reason the owner function returns an incorrect value for the entity is that the "reader" of the world snapshot does not know anything about other ownerships outside of its own. The owner ID is never even packed into the buffer for any of the entities, for any owner. So the "reader" can only know about ownership of their own entities and no others.
> 
> To add that support, as the most straightforward option, you can leverage the `event->buffer`, write the desired value there on the "writer" side, and then read it back on the "reader" side for all entities that you wish.
> 
> Does it make sense?

Alright I see, yeah it makes total sense. I will simply pack the owner data myself in the create read/write events and take it from there. Thanks for the fast replies from both of you. Cheers!
