### ISSUE TITLE
Chunk limit issue.

### ISSUE THREAD

**Issue by Tonyx97** [zpl-c/librg#42]
Hi, I'm testing librg in a huge world and I need relatively small chunks, so I'm currently using 1024x1024x1 chunks with a size of 10 x 10 x UINT16_MAX. The problem comes when entities mess around chunks above 2^15, a chunk is supposed to be up to 2^63 but for some reason, events, world_write etc won't work if the entities' chunks are above 2^15. I checked the code to see if there was any cast somewhere messing with the int64_t but couldn't find it, any idea why this could be happening?

**Comment by inlife** [comment]
Hey @Tonyx97 

Very interesting problem, I'm going to test it out tomorrow or the day after and try to find the bug. Any pieces of code that would help replicate the issue would be of great help!

**Comment by Tonyx97** [comment]
Thanks for the quick reply, I will attach the actual test project, it's currently in debug & x86 because I'm implementing the library as part of my mod in an existing game which requires reversing and so on. There may be useless files in the project but everything needed is by the project file itself so it should compile right away.
[librg test.zip](https://github.com/zpl-c/librg/files/9530903/librg.test.zip)

**Comment by inlife** [comment]
Thank you for the details! I will take a look :)

**Comment by inlife** [comment]
Found the root cause, overflow indeed! 

Here is the place with fix: 5b42c08fe317b4ddcf6bb46974a86dc85b9bc567
(Also added a special test case to verify against that)

Going to push the new release now

**Comment by inlife** [comment]
Also, did you know you can just download a single header file from our [releases page](https://github.com/zpl-c/librg/releases)? 

That way, you won't have to download and set up all of the structure and build and link librg binaries as you did in your example

**Comment by Tonyx97** [comment]
Oh nice work! I'm so glad to see you fixed it :D
. Yeah I know about the single .h but actually I want a static library instead, matter of preferences :D

**Comment by inlife** [comment]
Got it!

Thank you for the report. Please let us know if you'll encounter any other problems.
