### ISSUE TITLE
Entity aren't removed for the owners

### ISSUE THREAD

**Issue by Lyuu17** [zpl-c/librg#44]
As title says, entities visibility seems like to have 'always' to owners instead of 'default'. Is this supposed to work like this or am I missing something?

I'm currently relying of the entity create/remove events to set the ownership.

**Comment by inlife** [comment]
Hey

Owned entities will never be excluded from the visibility:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/2182108/209527020-99040652-603f-41ab-b914-9ae635957a03.png">

**Comment by inlife** [comment]
Oh, and by the way, one thing that interests me: what use case you see for your own entity to be invisible? Maybe I missed something obvious in the logic. :)

**Comment by Lyuu17** [comment]
> Oh, and by the way, one thing that interests me: what use case you see for your own entity to be invisible? Maybe I missed something obvious in the logic. :)

I'm using the ownership as a syncer, so the owner syncs the entities and once is too far away reset the ownership and find someone else to sync those entities.

**Comment by inlife** [comment]
Thank you for the example!

After some thought I small discussion with @zpl-zak we decided to introduce this feature. It is available in the latest release: https://github.com/zpl-c/librg/releases/tag/v7.2.0

**Comment by Lyuu17** [comment]
I think there was a misunderstood. I didn't mean to use the invisibility to the owners, but the same functionality as the entity being removed from the client world itself once is out of sync radius for them

**Comment by inlife** [comment]
Now I am even more confused. It seems like I do not understand the problem. Could you explain in more detail?
