### ISSUE TITLE
Compile error in using C++

### ISSUE THREAD

**Issue by blkcatman** [zpl-c/librg#45]
An error `error: taking address of temporary array` occurred when compile C++ program include librg.h.
```
/home/user/app/src/librg.h: In function 'int32_t librg_world_fetch_owner(librg_world*, int64_t, int64_t*, size_t*)':
/home/user/app/src/librg.h:21559:59: error: taking address of temporary array
21559 |     return librg_world_fetch_ownerarray(world, (int64_t[]){owner_id}, 1, entity_ids, entity_amount);
```

### Temporary solution to the problem

It works to change the line L21559 in librg.h
```
    return librg_world_fetch_ownerarray(world, (int64_t[]){owner_id}, 1, entity_ids, entity_amount);
```
to
```
    int64_t owner_ids[1]; owner_ids[0] = owner_id;
    return librg_world_fetch_ownerarray(world, owner_ids, 1, entity_ids, entity_amount);
```

### Environment
- librg version: Release 7.2.0
- Build Environment
  - Build Tool: CMake
  - Compiler: gcc 10.2.1 (with -lstdc++)
- OS: Linux (Debian)
### Relative Issue
- https://github.com/zpl-c/librg/issues/39

**Comment by inlife** [comment]
Hey @blkcatman 

Indeed makes sense. I'll push a commit and a new version with a fix
Thanks!

**Comment by inlife** [comment]
v7.2.1 is published

**Comment by blkcatman** [comment]
@inlife Thanks! I tried v7.2.1, it works perfectly.
