### ISSUE TITLE
Handler data_size casting limits it to u16 precision per entity write

### ISSUE THREAD

**Issue by trsh** [zpl-c/librg#46]
![bbbbbbbbb](https://github.com/zpl-c/librg/assets/3727523/4ecff38c-092f-4d6a-9a9d-db432cb5dcf4)

If this is intended, why should handler return `int32_t` and not `u16`? I stumbled upon this, because I am sending kind of big packets and this just cuts it, without warning. 

**Update**

I think i see, `int32_t` because return negatives and handle those in some parts? So there is u16 precision limit per entity write?

**Comment by inlife** [comment]
Now I'm also wondering if u16 was too small for the job and u32 would be more beneficial in this specific case. Any thoughts on that?

**Comment by trsh** [comment]
> Now I'm also wondering if u16 was too small for the job and u32 would be more beneficial in this specific case. Any thoughts on that?

Yes. I think, u16 is small. With u32 we could create bigger writes per entity and its up to the library user to lower/split it, if this creates other kind of problems.

**Comment by inlife** [comment]
I'll look for optimal ways of upgrading this capacity

**Comment by inlife** [comment]
Hey @trsh !

I've released a new version with an optional (at least for now) compile-time flag that extends the event limit from u16 to i32. I know it's not ideal size of u32, but should still be a viable option.

The flag is `LIBRG_ENABLE_EXTENDED_EVENTBUFFER.`. It needs to be defined for the source part in the following fashion:

```c
#define LIBRG_ENABLE_EXTENDED_EVENTBUFFER
#define LIBRG_IMPL
#include "librg.h"
```

If the application is networked, both sides should have this defined.

I've also added runtime checks for the event buffer sizes, so at least the there will be some awareness about this issue, and updated the docs.

Let me know if that helps!

**Comment by trsh** [comment]
Closing this, as it seems to work as expected after some quick tests with my project.

Thank you!

I will open a new issue, if I encounter any problems regarding this.
